apiVersion: v1
kind: Service
metadata:
  name: ingester-service
  namespace: monitoring
spec:
  selector:
    app: ingester
  ports:
    - name: memberlist
      protocol: TCP
      port: 7946
      targetPort: 7946