apiVersion: v1
kind: Service
metadata:
  name: ingester-service
  namespace: monitoring
  annotations:
    prometheus.io/port: "3200"
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: ingester
  ports:
    - name: memberlist
      protocol: TCP
      port: 7946
      targetPort: 7946