apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-generator
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics-generator
  template:
    metadata:
      labels:
        app: metrics-generator
        system: tempo
    spec:
      nodeSelector:
        karpenter.sh/nodepool: general
      containers:
      - name: metrics-generator
        args: [ "-target=metrics-generator", "-config.file=/etc/tempo.yaml" ]
        image: grafana/tempo:latest
        ports:
        - containerPort: 7946
          name: memberlist
        - containerPort: 4317
          name: grpc
        resources:
          limits:
            cpu: 1000m
            memory: 1024Mi
          requests:
            cpu: 700m
            memory: 768Mi
        volumeMounts:
        - mountPath: /etc/tempo.yaml
          name: tempo-config
          subPath: tempo.yaml
      volumes:
      - name: tempo-config
        configMap: 
          name: tempo-configmap