apiVersion: apps/v1
kind: Deployment
metadata:
  name: distributor
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: distributor
  template:
    metadata:
      labels:
        app: distributor
        system: tempo
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchLabels:
                    app: distributor
                topologyKey: kubernetes.io/hostname
      nodeSelector:
        karpenter.sh/nodepool: general
      containers:
      - name: distributor
        args: [ "-target=distributor", "-config.file=/etc/tempo.yaml" ]
        image: pablommr/grafana-tempo:v2.8.1
        ports:
        - containerPort: 7946
          name: memberlist
        - containerPort: 4317
          name: grpc
        - containerPort: 3200
          name: http-metrics
        livenessProbe:
          httpGet:
            path: /ready
            port: http-metrics
          initialDelaySeconds: 45
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: http-metrics
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          limits:
            cpu: 2000m
            memory: 2Gi
          requests:
            cpu: 1700m
            memory: 2Gi
        volumeMounts:
        - mountPath: /etc/tempo.yaml
          name: tempo-config
          subPath: tempo.yaml
      volumes:
      - name: tempo-config
        configMap: 
          name: tempo-configmap