apiVersion: v1
kind: Service
metadata:
  name: distributor-service
  namespace: monitoring
spec:
  selector:
    app: distributor
  ports:
    - name: memberlist
      protocol: TCP
      port: 7946
      targetPort: 7946
    - name: gRPC
      protocol: TCP
      port: 4317
      targetPort: gRPC