apiVersion: v1
kind: Service
metadata:
  name: alloy-service
  namespace: monitoring
spec:
  selector:
    app: alloy
  ports:
    - name: gRPC
      protocol: TCP
      port: 4319
      targetPort: gRPC
    - name: HTTP
      protocol: TCP
      port: 4318
      targetPort: HTTP
    - name: METRICS
      protocol: TCP
      port: 12345
      targetPort: METRICS