apiVersion: v1
kind: Service
metadata:
  name: alloy-service
  namespace: monitoring
  annotations:
    prometheus.io/port: "12345"
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: alloy
  ports:
    - name: grpc
      protocol: TCP
      port: 4317
      targetPort: grpc
    - name: http
      protocol: TCP
      port: 4318
      targetPort: http
    - name: metrics
      protocol: TCP
      port: 12345
      targetPort: metrics