apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-configmap
  namespace: monitoring
data:
  tempo.yaml: |
    server:
      http_listen_port: 3200

    memberlist:
      abort_if_cluster_join_fails: false
      bind_port: 7946
      join_members:
      - ingester-service:7946
      - metrics-generator-service:7946
      
    distributor:
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: "0.0.0.0:4317"
            http:
              endpoint: "0.0.0.0:4318"

    metrics_generator:
      registry:
        external_labels:
          source: tempo
          cluster: docker-compose
      storage:
        path: /var/tempo/generator/wal
        remote_write:
          - url: http://prometheus-tempo-service:9090/api/v1/write
            send_exemplars: true
      traces_storage:
        path: /var/tempo/generator/traces

    querier:
      frontend_worker:
        frontend_address: query-frontend-service:9095

    storage:
      trace:
        backend: s3
        s3:
          bucket: "apm-tempo-development"
          region: "us-east-1"
          endpoint: s3.us-east-1.amazonaws.com
          access_key: ""
          secret_key: ""

    overrides:
      defaults:
        metrics_generator:
          processors: ['service-graphs', 'span-metrics', 'local-blocks']
          generate_native_histograms: both