apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-metrics-data-pvc
  namespace: monitoring
spec:
  storageClassName: "gp2"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi