apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-metrics-configmap
  namespace: monitoring
data:
  prometheus.yml: |-
    scrape_configs:
    - job_name: 'prometheus'
      scrape_interval: 30s
      static_configs:
      - targets: ['localhost:9090']
    - job_name: 'kube-state-metrics'
      scrape_interval: 30s
      relabel_configs:
      - target_label: cluster_name
        replacement: ''
        action: replace
      static_configs:
      - targets: ['kube-state-metrics.kube-system.svc.cluster.local:8080']
    - job_name: 'alloy'
      scrape_interval: 30s
      kubernetes_sd_configs:
      - role: endpoints
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_name]
        action: keep
        regex: alloy-service
      - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
        action: replace
        target_label: __address__
        regex: (.+)(?::\d+);(\d+)
        replacement: $1:$2
    - job_name: 'loki-canary'
      scrape_interval: 30s
      kubernetes_sd_configs:
      - role: endpoints
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_name]
        action: keep
        regex: loki-canary
      - source_labels: [__address__]
        action: keep
        regex: '.*:3500'
    - job_name: 'loki-compactor'
      scrape_interval: 30s
      kubernetes_sd_configs:
      - role: endpoints
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_name]
        action: keep
        regex: loki-compactor
      - source_labels: [__address__]
        action: keep
        regex: '.*:3100'
    - job_name: 'loki-distributor'
      scrape_interval: 30s
      kubernetes_sd_configs:
      - role: endpoints
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_name]
        action: keep
        regex: loki-distributor
      - source_labels: [__address__]
        action: keep
        regex: '.*:3100'
    - job_name: 'loki-index-gateway'
      scrape_interval: 30s
      kubernetes_sd_configs:
      - role: endpoints
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_name]
        action: keep
        regex: loki-index-gateway
      - source_labels: [__address__]
        action: keep
        regex: '.*:3100'
    - job_name: 'loki-ingester'
      scrape_interval: 30s
      kubernetes_sd_configs:
      - role: endpoints
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_name]
        action: keep
        regex: loki-ingester
      - source_labels: [__address__]
        action: keep
        regex: '.*:3100'
    - job_name: 'loki-querier'
      scrape_interval: 30s
      kubernetes_sd_configs:
      - role: endpoints
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_name]
        action: keep
        regex: loki-querier
      - source_labels: [__address__]
        action: keep
        regex: '.*:3100'
    - job_name: 'loki-query-frontend'
      scrape_interval: 30s
      kubernetes_sd_configs:
      - role: endpoints
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_name]
        action: keep
        regex: loki-query-frontend
      - source_labels: [__address__]
        action: keep
        regex: '.*:3100'
    - job_name: 'loki-query-scheduler'
      scrape_interval: 30s
      kubernetes_sd_configs:
      - role: endpoints
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_name]
        action: keep
        regex: loki-query-scheduler
      - source_labels: [__address__]
        action: keep
        regex: '.*:3100'
    - job_name: 'loki-ruler'
      scrape_interval: 30s
      kubernetes_sd_configs:
      - role: endpoints
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_name]
        action: keep
        regex: loki-ruler
      - source_labels: [__address__]
        action: keep
        regex: '.*:3100'
    - job_name: 'tempo-distributor'
      scrape_interval: 30s
      kubernetes_sd_configs:
      - role: endpoints
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_name]
        action: keep
        regex: distributor-service
      - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
        action: replace
        target_label: __address__
        regex: (.+)(?::\d+);(\d+)
        replacement: $1:$2
    - job_name: 'tempo-ingester'
      scrape_interval: 30s
      kubernetes_sd_configs:
      - role: endpoints
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_name]
        action: keep
        regex: ingester-service
      - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
        action: replace
        target_label: __address__
        regex: (.+)(?::\d+);(\d+)
        replacement: $1:$2
    - job_name: 'tempo-metrics-generator'
      scrape_interval: 30s
      kubernetes_sd_configs:
      - role: endpoints
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_name]
        action: keep
        regex: metrics-generator-service
      - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
        action: replace
        target_label: __address__
        regex: (.+)(?::\d+);(\d+)
        replacement: $1:$2
    - job_name: 'tempo-querier'
      scrape_interval: 30s
      kubernetes_sd_configs:
      - role: endpoints
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_name]
        action: keep
        regex: querier-service
      - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
        action: replace
        target_label: __address__
        regex: (.+)(?::\d+);(\d+)
        replacement: $1:$2
    - job_name: 'tempo-query-frontend'
      scrape_interval: 30s
      kubernetes_sd_configs:
      - role: endpoints
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_name]
        action: keep
        regex: query-frontend-service
      - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
        action: replace
        target_label: __address__
        regex: (.+)(?::\d+);(\d+)
        replacement: $1:$2
    - job_name: 'tempo-compactor'
      scrape_interval: 30s
      kubernetes_sd_configs:
      - role: endpoints
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_name]
        action: keep
        regex: compactor-service
      - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
        action: replace
        target_label: __address__
        regex: (.+)(?::\d+);(\d+)
        replacement: $1:$2