apiVersion: v1
kind: Service
metadata:
  name: prometheus-metrics-service
  namespace: monitoring
spec:
  ports:
  - port: 9090
    targetPort: prom-port
    protocol: TCP
    name: prometheus
  selector:
    app: prometheus-metrics