    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
     labels:
       app.kubernetes.io/component: statefulset
       app.kubernetes.io/name: prometheus-metrics
     name: prom-tempo-crb
     namespace: monitoring
    roleRef:
     apiGroup: rbac.authorization.k8s.io
     kind: ClusterRole
     name: prom-tempo-cr
    subjects:
     - kind: ServiceAccount
       name: prometheus-metrics-sa
       namespace: monitoring