apiVersion: v1
kind: Service
metadata:
  name: compactor-service
  namespace: monitoring
  annotations:
    prometheus.io/port: "3200"
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: compactor
  ports:
    - name: memberlist
      protocol: TCP
      port: 7946
      targetPort: 7946
    - name: grpc
      protocol: TCP
      port: 4317
      targetPort: grpc