apiVersion: apps/v1
kind: Deployment
metadata:
  name: compactor
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: compactor
  template:
    metadata:
      labels:
        app: compactor
        system: tempo
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchLabels:
                    app: compactor
                topologyKey: kubernetes.io/hostname
      nodeSelector:
        karpenter.sh/nodepool: general
      containers:
      - name: compactor
        args: [ "-target=compactor", "-config.file=/etc/tempo.yaml" ]
        image: pablommr/grafana-tempo:v2.8.1
        ports:
        - containerPort: 7946
          name: memberlist
        - containerPort: 4317
          name: grpc
        - containerPort: 3200
          name: http-metrics
        livenessProbe:
          httpGet:
            path: /ready
            port: http-metrics
          initialDelaySeconds: 45
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          limits:
            cpu: 1000m
            memory: 6Gi
          requests:
            cpu: 700m
            memory: 6Gi
        volumeMounts:
        - mountPath: /etc/tempo.yaml
          name: tempo-config
          subPath: tempo.yaml
      volumes:
      - name: tempo-config
        configMap: 
          name: tempo-configmap