apiVersion: apps/v1
kind: Deployment
metadata:
  name: querier
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: querier
  template:
    metadata:
      labels:
        app: querier
        system: tempo
    spec:
      nodeSelector:
        karpenter.sh/nodepool: general
      containers:
      - name: querier
        args: [ "-target=querier", "-config.file=/etc/tempo.yaml" ]
        image: pablommr/grafana-tempo:v2.8.1
        ports:
        - containerPort: 3200
          name: frontend
        - containerPort: 7946
          name: memberlist
        livenessProbe:
          httpGet:
            path: /ready
            port: frontend
          initialDelaySeconds: 45
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: frontend
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          limits:
            cpu: 300m
            memory: 6Gi
          requests:
            cpu: 200m
            memory: 6Gi
        volumeMounts:
        - mountPath: /etc/tempo.yaml
          name: tempo-config
          subPath: tempo.yaml
      volumes:
      - name: tempo-config
        configMap: 
          name: tempo-configmap