apiVersion: apps/v1
kind: Deployment
metadata:
  name: querier
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: querier
  template:
    metadata:
      labels:
        app: querier
        system: tempo
    spec:
      nodeSelector:
        karpenter.sh/nodepool: general
      containers:
      - name: querier
        args: [ "-target=querier", "-config.file=/etc/tempo.yaml" ]
        image: grafana/tempo:latest
        resources:
          limits:
            cpu: 300m
            memory: 1024Mi
          requests:
            cpu: 200m
            memory: 768Mi
        volumeMounts:
        - mountPath: /etc/tempo.yaml
          name: tempo-config
          subPath: tempo.yaml
      volumes:
      - name: tempo-config
        configMap: 
          name: tempo-configmap