apiVersion: v1
kind: Service
metadata:
  name: querier-service
  namespace: monitoring
  annotations:
    prometheus.io/port: "3200"
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: querier
  ports:
    - name: metrics
      protocol: TCP
      port: 3000
      targetPort: 3000