apiVersion: v1
kind: Service
metadata:
  name: query-frontend-service
  namespace: monitoring
  annotations:
    prometheus.io/port: "3200"
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: query-frontend
  ports:
    - name: qf-port
      protocol: TCP
      port: 9095
      targetPort: 9095