apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-frontend
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: query-frontend
  template:
    metadata:
      labels:
        app: query-frontend
        system: tempo
    spec:
      nodeSelector:
        karpenter.sh/nodepool: general
      containers:
      - name: query-frontend
        args: [ "-target=query-frontend", "-config.file=/etc/tempo.yaml" ]
        image: grafana/tempo:latest
        ports:
        - containerPort: 3200
          name: frontend
        - containerPort: 9095
          name: qf-port
        - containerPort: 7946
          name: memberlist
        livenessProbe:
          httpGet:
            path: /ready
            port: frontend
          initialDelaySeconds: 45
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          limits:
            cpu: 300m
            memory: 4Gi
          requests:
            cpu: 200m
            memory: 4Gi
        volumeMounts:
        - mountPath: /etc/tempo.yaml
          name: tempo-config
          subPath: tempo.yaml
      volumes:
      - name: tempo-config
        configMap: 
          name: tempo-configmap