apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-tempo-configmap
  namespace: monitoring
data:
  prometheus.yml: |-
    scrape_configs:
    - job_name: 'prometheus'
      scrape_interval: 30s
      static_configs:
      - targets: ['localhost:9090']